#!/bin/bash
# HW4
# Xuecheng Liu

# check number of argument
if [ "$#" -lt 2 ]
then
    echo 'Error: should be exactly 2 arguments' >&2
    exit 1
fi

# check existence of output file
if [ -f "$1" ]
then
    echo "Warning: output file already exits and will be overwritten" >&2
    rm "$1"
fi

# check existence of input file
if [ ! -f "$2" ]
then
    echo "Error: html file does not exist" >&2
    exit 1
fi

grep -Eo 'href[="./_?a-zA-Z0-9]+.c"' "$2" | grep -Eo '[./_?a-zA-Z0-9]+.c' |
sed 's#\.\.#https://courses.cs.washington.edu/courses/cse374/22au#g' >> "$1"
exit 0
