Script started on 2022-10-12 19:38:59-07:00 [TERM="xterm-256color" TTY="/dev/pts/101" COLUMNS="80" LINES="24"]
[?2004h[xl0306@cancun ~]$ mkdir HW1
[?2004l[?2004h[xl0306@cancun ~]$ cd HW1
[?2004l[?2004h[xl0306@cancun HW1]$ pwd
[?2004l/data/netid/xl0306/HW1
[?2004h[xl0306@cancun HW1]$ echo "This is Fu[K[Kfun"
[?2004lThis is fun
[?2004h[xl0306@cancun HW1]$ echo "This is fun" > wno[K[K[K[Know[K[K[K now
[?2004l[?2004h[xl0306@cancun HW1]$ echo[K[K[K[Kdate >> now
[?2004l[?2004h[xl0306@cancun HW1]$ uname -v >> now
[?2004l[?2004h[xl0306@cancun HW1]$ wc -l now
[?2004l3 now
[?2004h[xl0306@cancun HW1]$ more now
[?2004lThis is fun
Wed Oct 12 07:40:35 PM PDT 2022
#1 SMP PREEMPT Tue Sep 20 17:53:31 UTC 2022
[?2004h[xl0306@cancun HW1]$ cp now pastnow
[?2004l[?2004h[xl0306@cancun HW1]$ cd ~
[?2004l[?2004h[xl0306@cancun ~]$ find ![K~/HW1/pastnow
[?2004l/data/netid/xl0306/HW1/pastnow
[?2004h[xl0306@cancun ~]$ cd HW1
[?2004l[?2004h[xl0306@cancun HW1]$ ls -l
[?2004ltotal 8
-rw-r--r-- 1 xl0306 netid 88 Oct 12 19:40 now
-rw-r--r-- 1 xl0306 netid 88 Oct 12 19:41 pastnow
[?2004h[xl0306@cancun HW1]$ chmod 511 now
[?2004l[?2004h[xl0306@cancun HW1]$ ls -l
[?2004ltotal 8
-r-x--x--x 1 xl0306 netid 88 Oct 12 19:40 [0m[01;32mnow[0m
-rw-r--r-- 1 xl0306 netid 88 Oct 12 19:41 pastnow
[?2004h[xl0306@cancun HW1]$ cd~[K~[K
[?2004l[?2004h[xl0306@cancun ~]$ vi .bashrc
[?2004l[?1049h[22;0;0t[>4;2m[?1h=[?2004h[?1004h[1;24r[?12h[?12l[22;2t[22;1t[27m[23m[29m[m[H[2J[?25l[24;1H".bashrc" 28L, 509B[2;1H▽[6n[2;1H  [3;1HPzz\[0%m[6n[3;1H           [1;1H[>c]10;?]11;?[2;1H[34m# User specific environment[m[2;28H[K[3;1H[38;5;130mif ![m [35m[[[m [38;5;130m"[m[35m$PATH[m[38;5;130m"[m [38;5;130m=~[m [38;5;130m"[m[35m$HOME[m[31m/.local/bin:[m[35m$HOME[m[31m/bin:[m[38;5;130m"[m [35m]][m[3;52H[K[4;1H[38;5;130mthen[m
    [35mPATH[m[38;5;130m="[m[35m$HOME[m[31m/.local/bin:[m[35m$HOME[m[31m/bin:[m[35m$PATH[m[38;5;130m"
fi
export[m PATH

[34m# Uncomment the following line if you don't like systemctl's auto-paging featuree[10;1H:
# export SYSTEMD_PAGER=

# User specific aliases and functions[m
[38;5;130mif [[m [38;5;130m-d[m ~/.bashrc.d [38;5;130m];[m [38;5;130mthen[15;9Hfor[m rc [38;5;130min[m ~/.bashrc.d/*[38;5;130m;[m [38;5;130mdo[16;17Hif [[m [38;5;130m-f[m [38;5;130m"[m[35m$rc[m[38;5;130m"[m [38;5;130m];[m [38;5;130mthen[17;17H        . "[m[35m$rc[m[38;5;130m"[18;17Hfi[19;9Hdone
fi

alias [m[36mll[m[38;5;130m="[m[31mls -l[m[38;5;130m"
unset[m[36m rc[m[24;63H27,1[10CBot[22;1H[?25h[?25l[24;53H:[22;1H[24;1H[K[24;1H:[?25hwq[?25l[?2004l[>4;m".bashrc" 28L, 509B written[23;2t[23;1t
[?1004l[?2004l[?1l>[?25h[>4;m[?1049l[23;0;0t[?2004h[xl0306@cancun ~]$ emacs .bashrc
[?2004l[?1049h[22;0;0t[?12;25h[?1h=[H[2J[24d[K[?1l>[?12l[?25h[?1049l[23;0;0t[39;49m[?1049h[22;0;0t[?12;25h[?1h=[H[2J[23d[?25l[30m[47m-UUU:----F1  [39;49m[1m[30m[47m*scratch*   [0m[39;49m[30m[47m   All L1     (Fundamental) ---------------------------[39;49m
[A[2d[?12l[?25h[?12;25h[24d[?25le[K[H[7mFile Edit Options Buffers Tools Help                                            [0m[39;49m[27m
[A
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[30m[47m-UUU:----F1  [39;49m[1m[30m[47m*scratch*   [0m[39;49m[30m[47m   All L1     (Fundamental) ---------------------------[39;49m
[A
Loading /usr/share/emacs/site-lisp/site-start.d/autoconf-init.el (source)...don\
[A[2d[?12l[?25h[?12;25h[24d[K[23;49H[?25lcmake-init.el (source)...[K[H
[?12l[?25h[?12;25h[23;74H[?25ldone[H
[?12l[?25h[?12;25h[24d[?25lrce)...[23;49Hdesktop-entry-mode-init.el (sou\
[2d[?12l[?25h[?12;25h[24;8H[?25ldone[H
[?12l[?25h[?12;25h[24d[?25l)...[K[23;49Hmercurial-site-start.el (source[H
[?12l[?25h[?12;25h[24;5H[?25ldone[H
[?12l[?25h[?12;25h[>0c[?2004h[?1004h[24d[?25lFor information about GNU Emacs and the GNU system, type C-h C-a.[K[H[7mFile Edit Options Buffers Tools Lisp-Interaction Help                           [0m[39;49m[27m
[A
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[30m[48;5;250m-UUU:----F1  [39;49m[1m[30m[48;5;250m*scratch*   [0m[39;49m[30m[48;5;250m   All L1     (Lisp Interaction ElDoc) ----------------[39;49m
[A[2d[?12l[?25h[?12;25h[24d[?25lSetting up indent for shell type bash[K[H
[?12l[?25h[?12;25h[24d[?25lIndentation variables are now local.[K[H
[?12l[?25h[?12;25h[24;13H[?25lsetup for shell type bash[H
[?12l[?25h[?12;25h[24d[?25lIndentation setup for shell type bash[K[H[7mFile Edit Options Buffers Tools Sh-Script Help                                  [0m[39;49m[27m
[A
[38;5;124m# .bashrc [39;49m                                                                      
[A
[K
[38;5;124m# Source global definitions [39;49m                                                    
[A
[38;5;129mif[39;49m [ -f /etc/bashrc ]; [38;5;129mthen[39;49m[K
        [38;5;60m.[39;49m /etc/bashrc[K
[38;5;129mfi[39;49m[K
[K
[38;5;124m# User specific environment [39;49m                                                    
[A
[38;5;129mif[39;49m ! [[ [38;5;89m"$PATH"[39;49m =~ [38;5;89m"$HOME/.local/bin:$HOME/bin:"[39;49m ]][K
[38;5;129mthen[39;49m[K
    [38;5;130mPATH[39;49m=[38;5;89m"$HOME/.local/bin:$HOME/bin:$PATH"[39;49m[K
[38;5;129mfi[39;49m[K
[38;5;60mexport[39;49m PATH[K
[K
[38;5;124m# Uncomment the following line if you don't like systemctl's auto-paging featur[39;49m\
[A
[38;5;124me: [39;49m                                                                             
[A
[38;5;124m# export SYSTEMD_PAGER= [39;49m                                                        
[A
[K
[38;5;124m# User specific aliases and functions [39;49m                                          
[A
[38;5;129mif[39;49m [ -d ~/.bashrc.d ]; [38;5;129mthen[39;49m[K
        [38;5;129mfor[39;49m rc[38;5;129m in[39;49m ~/.bashrc.d/*; [38;5;129mdo[39;49m[K
[30m[48;5;250m-UU-:----F1  [39;49m[1m[30m[48;5;250m.bashrc     [0m[39;49m[30m[48;5;250m   Top L1     (Shell-script[bash]) --------------------[39;49m
[A[2d[?12l[?25h[?12;25h[24d[K[2d[24d[K[?1004l[?2004l[?1l>[?12l[?25h[?1049l[23;0;0t[39;49m[?2004h[xl0306@cancun ~]$ source .bashrc
[?2004l[?2004h[xl0306@cancun ~]$ ll
[?2004ltotal 4
drwxr-xr-x 2 xl0306 netid  113 Oct 10 21:00 [0m[01;34mcse374[0m
drwxr-xr-x 2 xl0306 netid   44 Oct 12 19:41 [01;34mHW1[0m
-rw-r--r-- 1 xl0306 netid 4096 Oct 12 19:44 hw1.script
[?2004h[xl0306@cancun ~]$ emacs
[?2004l[?1049h[22;0;0t[?12;25h[?1h=[H[2J[24d[K[?1l>[?12l[?25h[?1049l[23;0;0t[39;49m[?1049h[22;0;0t[?12;25h[?1h=[H[2J[23d[?25l[30m[47m-UUU:----F1  [39;49m[1m[30m[47m*scratch*   [0m[39;49m[30m[47m   All L1     (Fundamental) ---------------------------[39;49m
[A[2d[?12l[?25h[?12;25h[24d[?25le[K[H[7mFile Edit Options Buffers Tools Help                                            [0m[39;49m[27m
[A
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[30m[47m-UUU:----F1  [39;49m[1m[30m[47m*scratch*   [0m[39;49m[30m[47m   All L1     (Fundamental) ---------------------------[39;49m
[A
Loading /usr/share/emacs/site-lisp/site-start.d/autoconf-init.el (source)...don\
[A[2d[?12l[?25h[?12;25h[24d[K[23;49H[?25lcmake-init.el (source)...[K[H
[?12l[?25h[?12;25h[23;74H[?25ldone[H
[?12l[?25h[?12;25h[24d[?25lrce)...[23;49Hdesktop-entry-mode-init.el (sou\
[2d[?12l[?25h[?12;25h[24;8H[?25ldone[H
[?12l[?25h[?12;25h[24d[?25l)...[K[23;49Hmercurial-site-start.el (source[H
[?12l[?25h[?12;25h[24;5H[?25ldone[H
[?12l[?25h[?12;25h[>0c[?2004h[?1004h[24d[?25lFor information about GNU Emacs and the GNU system, type C-h C-a.[K[H[7mFile Edit Options Buffers Tools Lisp-Interaction Help                           [0m[39;49m[27m
[A
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[30m[48;5;250m-UUU:----F1  [39;49m[1m[30m[48;5;250m*scratch*   [0m[39;49m[30m[48;5;250m   All L1     (Lisp Interaction ElDoc) ----------------[39;49m
[A[2d[?12l[?25h[?12;25h[24d[?25lFor information about GNU Emacs and the GNU system, type C-h C-a.[K[H[7mFile Edit Options Buffers Tools Help                                            [0m[39;49m[27m
[A
Welcome to GNU Emacs, one component of the GNU/Linux operating system.[K
[K
Get help           C-h  (Hold down CTRL and press h)[K
[4m[38;5;62mEmacs manual[0m[39;49m       C-h r        [4m[38;5;62mBrowse manuals[0m[39;49m     C-h i[K
[4m[38;5;62mEmacs tutorial[0m[39;49m     C-h t        Undo changes       C-x u[K
[4m[38;5;62mBuy manuals[0m[39;49m        C-h RET      Exit Emacs         C-x C-c[K
[4m[38;5;62mActivate menubar[0m[39;49m   M-`[K
(‘C-’ means use the CTRL key.  ‘M-’ means use the Meta (or Alt) key.[K
If you have no Meta key, you may instead type ESC followed by the character.)[K
Useful tasks:[K
[4m[38;5;62mVisit New File[0m[39;49m                  [4m[38;5;62mOpen Home Directory[0m[39;49m[K
[4m[38;5;62mCustomize Startup[0m[39;49m               [4m[38;5;62mOpen *scratch* buffer[0m[39;49m[K
[K
GNU Emacs 27.2 (build 1, x86_64-redhat-linux-gnu, GTK+ Version 3.24.31, cairo v\
[A
ersion 1.17.4)[K
 of 2022-06-02[K
Copyright (C) 2021 Free Software Foundation, Inc.[K
[K
GNU Emacs comes with ABSOLUTELY NO WARRANTY; type C-h C-w for [4m[38;5;62mfull details[0m[39;49m.[K
Emacs is Free Software--Free as in Freedom--so you can redistribute copies[K
of Emacs and modify it; type C-h C-c to see [4m[38;5;62mthe conditions[0m[39;49m.[K
[30m[48;5;250m-UUU:%%--F1  [39;49m[1m[30m[48;5;250m*GNU Emacs* [0m[39;49m[30m[48;5;250m   Top L1     (Fundamental) ---------------------------[39;49m
[A[2d[?12l[?25h[?12;25h[24d[K[?1004l[?2004l[?1l>[?12l[?25h[?1049l[23;0;0t[39;49m
[1]+  Stopped                 emacs
[?2004h[xl0306@cancun ~]$ fg
[?2004lemacs
[?1049h[22;0;0t[?12;25h[?1h=[?1004h[?2004h[24;1H[K[H[?25l[7mFile Edit Options Buffers Tools Help                                            [0m[39;49m[27m
[A
Welcome to GNU Emacs, one component of the GNU/Linux operating system.[K
[K
Get help           C-h  (Hold down CTRL and press h)[K
[4m[38;5;62mEmacs manual[0m[39;49m       C-h r        [4m[38;5;62mBrowse manuals[0m[39;49m     C-h i[K
[4m[38;5;62mEmacs tutorial[0m[39;49m     C-h t        Undo changes       C-x u[K
[4m[38;5;62mBuy manuals[0m[39;49m        C-h RET      Exit Emacs         C-x C-c[K
[4m[38;5;62mActivate menubar[0m[39;49m   M-`[K
(‘C-’ means use the CTRL key.  ‘M-’ means use the Meta (or Alt) key.[K
If you have no Meta key, you may instead type ESC followed by the character.)[K
Useful tasks:[K
[4m[38;5;62mVisit New File[0m[39;49m                  [4m[38;5;62mOpen Home Directory[0m[39;49m[K
[4m[38;5;62mCustomize Startup[0m[39;49m               [4m[38;5;62mOpen *scratch* buffer[0m[39;49m[K
[K
GNU Emacs 27.2 (build 1, x86_64-redhat-linux-gnu, GTK+ Version 3.24.31, cairo v\
[A
ersion 1.17.4)[K
 of 2022-06-02[K
Copyright (C) 2021 Free Software Foundation, Inc.[K
[K
GNU Emacs comes with ABSOLUTELY NO WARRANTY; type C-h C-w for [4m[38;5;62mfull details[0m[39;49m.[K
Emacs is Free Software--Free as in Freedom--so you can redistribute copies[K
of Emacs and modify it; type C-h C-c to see [4m[38;5;62mthe conditions[0m[39;49m.[K
[30m[48;5;250m-UUU:%%--F1  [39;49m[1m[30m[48;5;250m*GNU Emacs* [0m[39;49m[30m[48;5;250m   Top L1     (Fundamental) ---------------------------[39;49m
[A[2d[?12l[?25h[?12;25h[24d[K[?1004l[?2004l[?1l>[?12l[?25h[?1049l[23;0;0t[39;49m
[1]+  Stopped                 emacs
[?2004h[xl0306@cancun ~]$ ps
[?2004l    PID TTY          TIME CMD
 536318 pts/102  00:00:00 bash
 536475 pts/102  00:00:00 emacs
 536481 pts/102  00:00:00 ps
[?2004h[xl0306@cancun ~]$ ps | grep "emacs"
[?2004l 536475 pts/102  00:00:00 [01;31m[Kemacs[m[K
[?2004h[xl0306@cancun ~]$ kill 536475
[?2004l[?2004h[xl0306@cancun ~]$ ps
[?2004l    PID TTY          TIME CMD
 536318 pts/102  00:00:00 bash
 536475 pts/102  00:00:00 emacs
 536537 pts/102  00:00:00 ps
[?2004h[xl0306@cancun ~]$ k[Kkill -9 [53[K[K[K536475
[?2004l[?2004h[xl0306@cancun ~]$ ps
[?2004l    PID TTY          TIME CMD
 536318 pts/102  00:00:00 bash
 536582 pts/102  00:00:00 ps
[1]+  Killed                  emacs
[?2004h[xl0306@cancun ~]$ echo "$USER rocks!"
[?2004lxl0306 rocks!
[?2004h[xl0306@cancun ~]$ exit
[?2004lexit

Script done on 2022-10-12 19:49:09-07:00 [COMMAND_EXIT_CODE="0"]
