Script started on 2022-10-03 12:43:44-07:00 [TERM="xterm-256color" TTY="/dev/pts/1" COLUMNS="80" LINES="24"]
[?2004h[xl0306@cancun cse374]$ [7mecho $SHELL[27mecho $SHELL
[?2004l/bin/bash
[?2004h[xl0306@cancun cse374]$ whoami
[?2004lxl0306
[?2004h[xl0306@cancun cse374]$ pwd
[?2004l/data/netid/xl0306/cse374
[?2004h[xl0306@cancun cse374]$ uname -a
[?2004lLinux cancun.cs.washington.edu 5.14.0-70.26.1.el9_0.x86_64 #1 SMP PREEMPT Tue Sep 20 17:53:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
[?2004h[xl0306@cancun cse374]$ gcc --v[K[K[K[K[K[K[K[7mgcc --version -std=c11[27mgcc --version -std=c11
[?2004lgcc (GCC) 11.2.1 20220127 (Red Hat 11.2.1-9)
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[?2004h[xl0306@cancun cse374]$ exit
[?2004lexit

Script done on 2022-10-03 12:45:24-07:00 [COMMAND_EXIT_CODE="0"]
